name: CI - Build Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: shaheen
          POSTGRES_PASSWORD: shaheen
          POSTGRES_DB: customer
          PGDATA: /data/postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: |
          cd backend
          mvn -ntp -B verify